spring.application.name=producto-service

# Conexión a la Base de Datos inyectada por variables de entorno
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/innovatech_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true